### ISSUE TITLE
Support for output file in JSON format

### ISSUE THREAD

**Issue by NotoriousRebel** [g0ldencybersec/CloudRecon#1]
While a sqlite3 DB has it's pros, typically the more output formats the merrier. Especially with the advent of the latest release of [jq](https://github.com/jqlang/jq/releases/tag/jq-1.7) just happening 5 days ago after a 5 year hiatus, it would be great for a `-o` option with the scrape command to write the data in a JSON file. This would allow for easier post processing in certain use cases and is typically a lot more flexible than a sqlite3 DB.

**Comment by mr-rizwan-syed** [comment]
It would be great, if scrape module also extract organization_name.

**Comment by mr-rizwan-syed** [comment]
#4 Resolved

**Comment by g0ldencybersec** [comment]
I merged the pull request to fix this! Thank you so much @mr-rizwan-syed !
